<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Authors>Typezer∅</Authors>
    <Company>Typezer∅ Studio</Company>
    <Product>Cadence Studio</Product>
    <Copyright>Copyright © Typezer∅</Copyright>
  </PropertyGroup>
</Project>
